name: BorrowedTime
version: 1.0.0
main: io.papermc.borrowedtime.Main
description: A plugin where time is of the essence...
author: pairnon
website: https://papermc.io
api-version: '1.20'
commands:
  sellhand:
    description: Sell the stack in your hand
    usage: /sellhand
  sellall:
    description: Sell all stacks that match your hand
    usage: /sellall
  values:
    description: View item values
    usage: /values