name: BorrowedTime
version: 1.0.0
main: io.papermc.borrowedtime.BorrowedTime
description: A plugin where time is of the essence...
author: pairnon
website: https://papermc.io
api-version: '1.20'
commands:
  freedirt:
    description: Free dirt?
    usage: /freedirt
  sell:
    description: Sell what is in your hand
    usage: /sell
  get:
    description: Get literally anything
    usage: /get <item> <amount>