name: BorrowedTime
version: 1.0.0
main: io.papermc.borrowedtime.BorrowedTime
description: A plugin where time is of the essence...
author: pairnon
website: https://papermc.io
api-version: '1.20'
commands:
  sellhand:
    description: Sell the item in your hand
    usage: /sellhand
  sellall:
    description: Sell every item in your inventory that matches your hand
    usage: /sellall
  values:
    description: View item values
    usage: /values